# スーパーマーケットA店のレイアウト定義
facility:
  name: "スーパーマーケットA"
  type: "retail"
  address: "東京都〇〇区〇〇1-2-3"
  dimensions:
    width: 100  # メートル
    height: 50
    floors: 1

# ゾーン定義
zones:
  - id: "entrance"
    name: "入口"
    type: "entrance"
    floor: 1
    polygon: [[0, 20], [10, 20], [10, 30], [0, 30]]
    capacity: 20
    
  - id: "vegetables"
    name: "野菜売場"
    type: "sales_area"
    floor: 1
    polygon: [[10, 0], [30, 0], [30, 20], [10, 20]]
    capacity: 30
    category: "fresh"
    
  - id: "meat_fish"
    name: "精肉・鮮魚"
    type: "sales_area"
    floor: 1
    polygon: [[30, 0], [60, 0], [60, 20], [30, 20]]
    capacity: 40
    category: "fresh"
    
  - id: "dairy"
    name: "乳製品・冷蔵"
    type: "sales_area"
    floor: 1
    polygon: [[60, 0], [80, 0], [80, 20], [60, 20]]
    capacity: 25
    category: "refrigerated"
    
  - id: "frozen"
    name: "冷凍食品"
    type: "sales_area"
    floor: 1
    polygon: [[10, 20], [30, 20], [30, 35], [10, 35]]
    capacity: 20
    category: "frozen"
    
  - id: "beverages"
    name: "飲料"
    type: "sales_area"
    floor: 1
    polygon: [[30, 20], [50, 20], [50, 35], [30, 35]]
    capacity: 25
    category: "beverages"
    
  - id: "snacks"
    name: "お菓子・パン"
    type: "sales_area"
    floor: 1
    polygon: [[50, 20], [70, 20], [70, 35], [50, 35]]
    capacity: 30
    category: "snacks"
    
  - id: "household"
    name: "日用品"
    type: "sales_area"
    floor: 1
    polygon: [[10, 35], [40, 35], [40, 50], [10, 50]]
    capacity: 35
    category: "household"
    
  - id: "cosmetics"
    name: "化粧品・医薬品"
    type: "sales_area"
    floor: 1
    polygon: [[40, 35], [60, 35], [60, 50], [40, 50]]
    capacity: 20
    category: "health_beauty"
    
  - id: "cashier"
    name: "レジエリア"
    type: "cashier"
    floor: 1
    polygon: [[70, 20], [100, 20], [100, 30], [70, 30]]
    capacity: 50
    registers: 8
    
  - id: "service_counter"
    name: "サービスカウンター"
    type: "service"
    floor: 1
    polygon: [[70, 30], [85, 30], [85, 35], [70, 35]]
    capacity: 10
    
  - id: "exit"
    name: "出口"
    type: "exit"
    floor: 1
    polygon: [[90, 30], [100, 30], [100, 40], [90, 40]]
    capacity: 20

# 制限エリア
restricted_areas:
  - id: "backyard"
    name: "バックヤード"
    floor: 1
    polygon: [[80, 0], [100, 0], [100, 20], [80, 20]]
    access_level: "staff_only"
    
  - id: "office"
    name: "事務所"
    floor: 1
    polygon: [[60, 45], [75, 45], [75, 50], [60, 50]]
    access_level: "manager_only"
    
  - id: "storage"
    name: "倉庫"
    floor: 1
    polygon: [[75, 35], [100, 35], [100, 50], [75, 50]]
    access_level: "staff_only"

# Bluetooth受信機配置
receivers:
  - id: "rcv_001"
    name: "入口受信機"
    position: [5, 25]
    floor: 1
    range: 30
    status: "active"
    
  - id: "rcv_002"
    name: "中央受信機1"
    position: [35, 10]
    floor: 1
    range: 30
    status: "active"
    
  - id: "rcv_003"
    name: "中央受信機2"
    position: [65, 10]
    floor: 1
    range: 30
    status: "active"
    
  - id: "rcv_004"
    name: "中央受信機3"
    position: [35, 40]
    floor: 1
    range: 30
    status: "active"
    
  - id: "rcv_005"
    name: "レジ受信機"
    position: [85, 25]
    floor: 1
    range: 30
    status: "active"
    
  - id: "rcv_006"
    name: "出口受信機"
    position: [95, 35]
    floor: 1
    range: 30
    status: "active"

# 通路定義
pathways:
  - id: "main_aisle"
    name: "メイン通路"
    type: "main"
    width: 3.0
    points: [[5, 25], [70, 25], [85, 25]]
    
  - id: "fresh_aisle"
    name: "生鮮通路"
    type: "secondary"
    width: 2.5
    points: [[20, 10], [70, 10]]
    
  - id: "center_aisle_1"
    name: "中央通路1"
    type: "secondary"
    width: 2.5
    points: [[20, 27.5], [70, 27.5]]
    
  - id: "center_aisle_2"
    name: "中央通路2"
    type: "secondary"
    width: 2.5
    points: [[25, 42.5], [55, 42.5]]

# POI (Point of Interest)
poi:
  - id: "promotion_1"
    name: "特売コーナー1"
    position: [15, 25]
    type: "promotion"
    
  - id: "promotion_2"
    name: "特売コーナー2"
    position: [50, 25]
    type: "promotion"
    
  - id: "sample_station"
    name: "試食コーナー"
    position: [45, 10]
    type: "sample"
    
  - id: "information"
    name: "インフォメーション"
    position: [75, 32.5]
    type: "information"